version: '3'

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 7000:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
